-- Crear tabla USUARIOCADS
CREATE TABLE IF NOT EXISTS USUARIOCADS (
    USUARIOCADS_ID VARCHAR(255) PRIMARY KEY,
    NOMBRE VARCHAR(255),
    APELLIDO1 VARCHAR(255),
    APELLIDO2 VARCHAR(255),
    CORREO VARCHAR(255) NOT NULL,
    CODIGO VARCHAR(255),
    TELEFONO VARCHAR(255),
    SIT_ACADEMICA VARCHAR(255),
    INSTITUCION VARCHAR(255),
    CIUDAD VARCHAR(255),
    DEPARTAMENTO VARCHAR(255),
    ESTADO VARCHAR(255),
    ES_USUARIO VARCHAR(255),
    FECHA_CREACION TIMESTAMP(6),
    FECHA_ACTUALIZACION TIMESTAMP(6),
    PASSWORD VARCHAR(255),
    PUESTO VARCHAR(255),
    USUARIO_ANT VARCHAR(255)
);
